# Generated by Django 4.0.5 on 2022-07-11 21:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('create_house', 'Can create a house model')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=40)),
                ('plot', models.CharField(max_length=10)),
                ('bathrooms', models.CharField(max_length=10)),
                ('bedrooms', models.CharField(max_length=10)),
                ('living_space', models.CharField(max_length=15)),
                ('plot_size', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(max_length=1000, upload_to='')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
