# Generated by Django 3.2.11 on 2022-06-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_house_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
            options={
                'permissions': [('create_house', 'Can create a house model')],
            },
        ),
    ]
