# Generated by Django 3.2.11 on 2022-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_broker_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
