# Generated by Django 3.2.11 on 2022-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220612_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
