# Generated by Django 3.2.11 on 2022-06-12 11:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_broker_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='broker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='broker',
            name='houses',
        ),
        migrations.AddField(
            model_name='house',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
