# Generated by Django 4.0.5 on 2022-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220612_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='country',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
