# Generated by Django 4.0.5 on 2022-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_house_city_house_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='plot_size',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='living_space',
            field=models.CharField(max_length=15),
        ),
    ]
