# Generated by Django 4.0.5 on 2022-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_house_plot_size_alter_house_living_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.CharField(max_length=10),
        ),
    ]
