# Generated by Django 4.0.5 on 2022-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_house_bathrooms_alter_house_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
